config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :users, only: [:index, :show, :update]
  resources :chatrooms, only: [:show, :create] do
    resources :messages, only: :create
  end
  resources :groups, only: [:index, :show, :destroy,] do
    resources :posts, only: [:create]
    resources :user_groups, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  has_one :chatroom_requester, class_name: 'User', foreign_key: :chatroom_requester_id
  has_one :chatroom_receiver, class_name: 'User', foreign_key: :chatroom_receiver_id
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups
  has_many :posts
  has_one_attached :photo

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  def self.search(category, location)
    where("category ILIKE ? and location ILIKE ?", "%#{category}%", "%#{location}%")
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :hobby
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :groups, through: :user_group, class_name: "Group", foreign_key: "user_id"

  has_many :posts, dependent: :destroy, class_name: "Post"

  has_many :messages, dependent: :destroy

  has_one_attached :photo

  validates_presence_of :first_name, :last_name, :email, :age, :about, :location

  validates :about, length: { minimum: 5 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_groups

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
  # validation - uniqueness user_group combination, then drop db and rails db:seed
  # validates :user_group, uniqueness: true
  validates :user, uniqueness: { scope: :group,
    message: "You've already joined the group" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # [...]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :about, :nickname ,:age, :location, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :nickname ,:about, :age, :location, :photo])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
    category = params[:category]
    location = params[:location]
    @groups = Group.search(category, location)
  end

  def show
    @group = Group.find(params[:id])
    @user_group = UserGroup.new
    @post = Post.new
    @markers = [
      {
        lat: @group.latitude,
        lng: @group.longitude
      }
    ]
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user

    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom, render_to_string(
          partial: "message",
          locals: { message: @message })
      )
      head :ok # dont send a view, dont make them re-direct
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private
  def message_params
    params.require(:message).permit(:content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @groups_all = Group.all
    @groups = @groups_all.sample(3)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ActionView::RecordIdentifier
  def create
    @group = Group.find(params[:group_id])
    @post = Post.new(post_params)
    @post.group = @group
    @post.user = current_user
    if @post.save
      dom = dom_id(@post)
      puts dom
      redirect_to group_path(@group, anchor: dom)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:content, :title)
  end
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  def create
    @group = Group.find(params[:group_id])
    @user_group = UserGroup.create!(group: @group, user: current_user)
    # @user_group.group = @group
    # @user_group.user = current_user
    # @user_group.save! # save permanently
    if @user_group.save
      redirect_to group_path(@group)
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  def index
    location = params[:location]
    min_age = params[:min_age]
    max_age = params[:max_age]
    gender = params[:gender]
    if params[:commit] && (!params[:min_age].present? || !params[:max_age].present? || !params[:location].present? || !params[:gender].present?)
      flash[:alert] = "Use the filters to search"
      @users = User.all
      # method that filters user array - current user id
    elsif params[:min_age].present?
      sql_query = "location ILIKE ? AND gender = ? AND age BETWEEN ? AND ?", "%#{location}%", "#{gender}", min_age, max_age
      @users = User.where(sql_query)
    else
      @users = User.all
      # logic here
    end
    # @users = User.search(location, min_age, max_age, gender).order("created_at ASC")
  end

  def show
    @user = User.find(params[:id])
    @markers = [
      {
        lat: @user.latitude,
        lng: @user.longitude
      }
    ]
    @chatroom_data = Chatroom.where(chatroom_requester_id: @user.id,  chatroom_receiver_id: current_user).first.present? ?
      Chatroom.where(chatroom_requester_id: @user.id, chatroom_receiver_id: current_user).first :
      Chatroom.where(chatroom_requester_id: current_user, chatroom_receiver_id: @user.id).first

    @user_groups = UserGroup.where(user_id: @user.id)
  end

  private

  # remove current user

  def set_user
    @user = User.find(params[:id])
  end

  def edit
  end

  # def update
  #   if @user.update(user_params)
  #     redirect_to @user, notice: 'Profile was successfuly updated.'
  #   end
  # end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :location, :age, :about, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/chatrooms/show.html.erb
<div class="container chatroom"
  data-controller="chatroom-subscription"
  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
>
  <h1 class="h1-chatroom"><%= @chatroom.name %></h1>
  <div class="messages" data-chatroom-subscription-target="messages" >
    <% @chatroom.messages.each do |message| %>
      <%= render "messages/message", message: message %>
      <% end %>
    </div>
  <%= simple_form_for [@chatroom, @message],
    html: {
      data: {
       action: "turbo:submit-end->chatroom-subscription#resetForm"
       },
      class: "d-flex" } do |f|
  %>
  <div class="message-type">
    <div class="message-box">
      <%= f.input :content,
        label: false,
        placeholder: "Message #{@chatroom.name}",
        wrapper_html: {class: "me-3"}
      %>
    </div>
    <div class="msg-send-btn">
      <%= f.submit "Send", class: "send-msg-btn" %>
    </div>
    <% end %>
  </div>
  <%# <%= button_to "Back to user profile", user_path, :method => "get", class: "btn btn-primary mb-3" %>
</div>

app/views/groups/index.html.erb
<div class="group-container-show-index">
  <div class="heading">
    <h2>There are <%= @groups.count %> groups near you</h2>
  </div>

  <%= form_tag(groups_path, :method => "get", id: "search-form") do %>
    <%= select_tag :location, options_for_select(["London", "Bristol", "Manchester", "Liverpool", "Cambridge", "Canterbury", "Birmingham", "Brighton", "Bath", "Reading" ],
        params[:location]), prompt: 'Any location', class: 'dropdown btn' %>
    <%= select_tag :category, options_for_select(["Sport & Fitness", "Films", "Technology", "Pets & Animals", "Music", "Art & Culture", ],
        params[:category]), prompt: 'Any category', class: 'dropdown btn' %>
    <%= submit_tag "Find", class: "submit-btn-group btn" %>
  <% end %>

  <div class="group-cards-container">
    <% @groups.each do |group| %>
    <div class="group-card">
      <img class="group-img-index" src=<%= group.image_url %> alt="">
      <div class="group-card-info">
        <h3><strong><%= link_to group.name, group_path(group), class: "group-name" %></strong></h3>
        <h4 class="group-category-index"><%= group.category %></h4>
        <h4 class="fw-bold group-location-index"><%= group.location %></h4>
        <p class="group-about-index"><%= group.about%></p>
      </div>
    </div>

    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<div class="user-container">
  <div class="user-show-content">
    <div class="user-profile">
      <div class="card user-profile-card-background">
        <img src="<%= @group.image_url %>">
        <h3 class="group-name-card"><%= @group.name %></h3>
        <%# <p>What we're about</p> %>
        <div>
          <p class="group-show-about"><%= @group.about %></p>
        </div>
        <%= simple_form_for [@group, @user_group] do |f| %>
        <%= submit_tag "Join group", class: "join-group-btn" %>
        <% end %>
        <div class="group-socials">
          <p>Share:</p>
           <i class="fa-brands fa-facebook"></i>
          <i id= "group-show-socials" class="fa-brands fa-instagram"></i>
          <i id= "group-show-socials" class="fa-brands fa-twitter"></i>
        </div>
      </div>
    </div>
    <div class="user-other" style="width: 100%; height: 300px;">
      <div class= "user-show-map" style="width: 500px; height: 255px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
      <div class="group-show-members">
        <h3 class="members">Members (<%= @group.user_groups.count %>)</h3><hr class="members-divider">
        <%# <p>See all</p> %>
        <% @group.user_groups.map do |user_group| %>
          <%= link_to (image_tag user_group.user.avatar_url, class: "group-show-avatar"), user_path(user_group.user) %>
        <% end %>
      </div>
    </div>
  </div>


  <h3 class="discussions-title">Discussions</h3>
  <div class="text-center discussion-container">
    <div class="discussion-card">
      <% @group.posts.each do |post| %>
        <%= content_tag :div, class: "card-title-container", id: dom_id(post) do %>
        <%# <div class="card-title-container"> %>
          <div class="card-title-item">
            <%= image_tag post.user.avatar_url, class:"avatar" %>
          </div>
          <div class="nickname-group-show discussion-card-title">
            <div class="member-name-created-at">
              <div class="card-title-item">
                <p class="nickname-discussion text-xl-left fw-bold"> <%= post.user.nickname %></p>
              </div>
              <div class="created-at-show card-title-item">
                <p class="created-at-align text-xl-left"><%= post.created_at.localtime.strftime("%e %b %Y, %H:%M") %></p>
              </div>
            </div>
            <div class="break"></div>
            <div class="card-title-item">
              <p class="post-content-group-show text-md-left"><%= post.content %></p>
            </div>
          </div>
        <%# </div> %>
        <% end %>
      <% end %>
    <%# <h4 class="post-your-comments">Post Your Comments</h4> %>
    </div>
    <%= simple_form_for([@group, @post]) do |f| %>
      <%= f.input :content, label: false, placeholder: "Write a comment", wrapper_html: { class: "" }%>
      <%= submit_tag "Post", class: "post-btn btn" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.10.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.10.0/mapbox-gl.css' rel='stylesheet' />
    <%# <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css"> %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="navbar-body-space">
    <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/messages/_message.html.erb
<div id="message- <%= message.id %>">
<small>
    <strong> <%= message.user.nickname %></strong>
    <i> <%= message.created_at.localtime.strftime("%e %b %Y, %H:%M")%></i>
  </small>
  <div class="message-group-received">
    <div class="message-received">
      <div class="message-received-text">
        <%= message.content %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="proposition">
  <div>
    <img src="https://fontmeme.com/permalink/220823/f9a4af9b09e0d2e134f6732fa04f98ec.png" alt="">
  </div>
  <div class="wrapper">
    <div class="typing-text">
      With Bonded, you can join communities and connect with new friends nearby!
    </div>
  </div>
</div>

<div id="about-us-div">
  <p id="about-us" class="about-bonded">Bonded is for people searching for real friendships and provides access to a community of people with shared interests!</p>
  <div id="our-values">
    <div class="d-flex flex-column align-items-center justify-content-center">
      <p>Community</p>
      <i class="fa-solid fa-people-group"></i>
    </div>
    <div class="d-flex flex-column align-items-center justify-content-center">
      <p>Authenticity</p>
      <i class="fa-regular fa-handshake"></i>
    </div>
    <div class="d-flex flex-column align-items-center justify-content-center">
      <p>Empathy</p>
      <i class="fa-solid fa-hand-holding-heart"></i>
    </div>
    <div class="d-flex flex-column align-items-center justify-content-center">
      <p>Loyalty</p>
      <i class="fa-solid fa-hands-holding-circle"></i>
    </div>
  </div>
</div>

<div class="choose-your-bond">
  <h2 id="action-heading" style="text-align: center"><strong>Choose your bond</strong></h2>
  <div class="options">
    <div>
    <%= button_to "Meet a friend", users_path, :method => "get", class: "bond-btn button-neon" %>
      <p class="btn-desc">Discover and chat with new people nearby<br>who share similar interests.</p>
    </div>
    <div>
      <%= button_to "Join a group", groups_path, :method => "get", class: "bond-btn button-neon" %>
      <p class="btn-desc">
        <span>Join groups and find communities<br>with common interests.</span>
      </p>
    </div>
  </div>
  <div class="container">
    <div class="explore-popular-groups">
      <h2><strong>Explore popular groups</strong></h2>
      <div class="group-cards-flexbox">
        <% @groups.each do |group| %>
          <div>
            <%= link_to group_path(group), class: "text-decoration-none text-dark" do %>
              <div>
                <img class="group-img-index-home" src=<%= group.image_url %> alt="">
                <div class="group-card-info-home">
                  <div><strong><%= link_to group.name, group_path(group), class: "group-name" %></strong></div>
                  <div class="card-text fw-bold"><span class="group-location"><%= group.location %></span></div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
        <%#= render 'shared/groupcards', groups: @groups %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= simple_form_for [@group, @post] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-body">
  <div class="footer-bonded">
    <div class="footer-wrapper">
      <div class="footer-social">
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class ="footer-contact" >
        <ul>
          <li>
          <p class="m-0"><strong>Contact us</strong></p>
          <a href="#">contact@teambonded.com</a></li>
          <li>
          <p class="m-0" ><strong>Press enquiries</strong></p>
          <a href="#">press@teambonded.com</a></li>
          <li>
          <p class="m-0"><strong>Something else?</strong></p>
          <a href="#">info@teambonded.com</a></li>
        </ul>
      </div>
      <div class = "footer-link" >
        <ul>
          <li>
          <a href="/">Home</a></li>
          <li>
          <a href="#">About us</a></li>
          <li>
          <a href="#">Privacy</a></li>
          <li>
          <a href="#">Terms</a></li>
          <li>Copyright 2022</li>
        </ul>
    </div>
  </div>
</div>

app/views/shared/_groupcards.html.erb
Shared _groupscard.html,erb

<div class="explore-group-cards-container ">
  <% @groups.each do |group| %>
    <div class="group-card col-sm-12 col-md-6 col-lg-4 col-xl-4">
      <%= link_to group_path(group), class: "text-decoration-none text-dark" do %>
        <div class="card-image"> <img class="group-img-index" src=<%= group.image_url %> alt=""></div>
          <div class="group-card-info">
            <div class="card-text fw-bold"><span class="text-secondary"> Groups in <%= group.location %></span></div>
              <div><strong><%= link_to group.name, group_path(group), class: "group-name" %></strong></div>
              <div class="group-text text-truncate"><%= group.about %></div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">

    <%= link_to root_path, class:"navbar-brand" do %>
      <%# <%= image_tag "https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,f_auto,q_auto:eco,dpr_1/bqag2d4y5czqb0vcepxv" %>
      <%# <strong id="logo">Bonded</strong> %>
      <%= image_tag "bonded-logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Explore Friends",users_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Explore Groups", groups_path, class: "nav-link" %>
          </li>
          <li class="nav-item avatar-dropdown">
            <%= image_tag "https://cdn2.stylecraze.com/wp-content/uploads/2013/11/Beautiful-Chinese-Women5.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="user-container">
  <div class="user-index-cards-header">
    <h2 class="user-index-cards-header-h2">
      Start bonding with new people<br>in your area!
    </h2>
  </div>
  <div class="user-index-cards-body-wrapper d-flex row justify-content-center">
    <div class="user-index-cards-search-body">
    <div class="user-index-steps">
      <i class="fa-solid fa-circle-arrow-right"></i>
      <p id="step-1">Filter by location, age, gender</p>
      <i class="fa-solid fa-circle-arrow-right"></i>
      <p id="step-2">Select your bond</p>
      <i class="fa-solid fa-circle-arrow-right"></i>
      <p id="step-3">Send them a message!</p>
      </p>
    </div>
      <%= form_tag(users_path, :method => "get", id: "user-search-form") do %>
        <%= select_tag :location, options_for_select(["London", "Bristol", "Manchester", "Liverpool", "Cambridge", "Canterbury", "Birmingham", "Brighton", "Bath", "Reading" ],
        params[:location]), prompt: 'Any location', class: 'dropdown btn qwerty' %>
        <%= select_tag :min_age, options_for_select(18..65, params[:min_age]), prompt: 'Min age', class: 'dropdown btn' %>
        <%= select_tag :max_age, options_for_select(18..65, params[:max_age]), prompt: 'Max age', class: 'dropdown btn' %>
        <%= select_tag :gender, options_for_select(["Male", "Female"], params[:gender]), prompt: 'Any gender', class: 'dropdown btn' %>
        <%= submit_tag "Find", class: 'index-search-btn btn-info' %>
      <% end %>
    </div>
    <div class="user-index-card row g-3">
      <% @users.each do |user| %>
        <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <div class="user-index-cards ">
              <div class="user-index-indiv-card">
              <div class="user-index-indiv-card-top">
                <div class="user-index-indiv-card-avatar">
                  <%# <% if user.photo.attached?  %>
                    <%# <%= cl_image_tag user.photo.key, height: 300, width: 400, crop: :fill, class:"avatar-large" %>
                  <%# <% else  %>
                  <%= image_tag user.avatar_url, class:"avatar-large" %>
                  <%# <% end %>
                </div>
                <div class="user-index-indiv-card-profile">
                <div class="my-profile">
                  <h3 class="user-index-indiv-card-profile-name">
                    <strong><%= link_to "#{user.first_name} #{user.last_name}", user_path(user), class: "user-index-name"  %></strong>
                  </h3>
                    <% if user == current_user %>
                      <p>My profile</p>
                    <% end %>
                </div>
                <div class="user-index-profile-info">
                  <p>
                    <i class="fa-solid fa-cake-candles"></i>
                    <%= user.age %>
                  </p>

                  <p>
                    <i class="fa-solid fa-venus-mars"></i>
                    <%= user.gender %>
                  </p>

                  <p>
                    <i class="map-dot-users fa-solid fa-location-dot"></i>
                    <%= user.location %>
                  </p>
                </div>
                  <p class="text-md-left"> <%= user.about %></p>
                  <%#= button_to "View Profile", user_path(user), :method => "get", class: "view-profile-btn" %>
                </div>
               </div>
              </div>
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-container">
  <div class="user-show-content">
    <div class="user-profile">
      <div class="card user-profile-card-background">
          <%# <% if @user.photo.attached?  %>
          <%# <%= cl_image_tag @user.photo.key, height: 300, width: 400, crop: :fill %>
          <%# <% else  %>
          <img src="<%= @user.avatar_url %>">
          <%# <% end %>
          <%# <%= simple_form_for(@user) do |f| %>
          <%# <%= f.input :photo, as: :file %>
          <%# <%= f.button :submit %>
          <%# <% end %>
        <h3 id="first-name"><%= @user.first_name %> <%= @user.last_name %></h3>
        <div class="user-info">
          <p><strong><%= @user.gender %></strong></p>
          <p><strong><%= @user.age %></strong></p>
          <p><strong><%= @user.location %></strong></p>
        </div>
        <div class="user-bio">
          <p class="user-show-about"><%= @user.about %></p>
        </div>
        <% if @user.id != current_user.id %>
          <%= button_to "Message", chatroom_path(@chatroom_data), :method => "get", class: "chat-btn" %>
        <% else %>
          <div class="empty-div"></div>
        <% end %>
        <div class="user-socials">
          <i class="fa-brands fa-facebook"></i>
          <i class="fa-brands fa-instagram"></i>
          <i class="fa-brands fa-twitter"></i>
        </div>
      </div>
    </div>
    <div class="user-other" style="width: 100%; height: 300px;">
      <div>
        <div class= "user-show-map" style="width: 500px; height: 255px;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
      <div class="user-show-groups">
        <h2 class="h2-groups">Groups (<%= @user.user_groups.count %>)</h2>
        <div class="user-show-group-card">
          <% @user_groups.each do |user_group| %>
            <div class="single-group-card">
              <%= image_tag(user_group.group.image_url, height: "80", style:"border-radius: 10px;") %>
              <%= link_to group_path(user_group.group) do %>
                <p class="user-show-group-name"><strong><%= user_group.group.name %></strong></p>
                <p class="user-show-group-location"><strong><%= user_group.group.location %></strong></p>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>